// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package internalhttp

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3c9d2b01DecodeGithubComMironorangeOtusGolangHwHw12131415CalendarInternalServerHttp(in *jlexer.Lexer, out *ListOfEvents) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(ListOfEvents, 0, 0)
			} else {
				*out = ListOfEvents{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 Event
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c9d2b01EncodeGithubComMironorangeOtusGolangHwHw12131415CalendarInternalServerHttp(out *jwriter.Writer, in ListOfEvents) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v ListOfEvents) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c9d2b01EncodeGithubComMironorangeOtusGolangHwHw12131415CalendarInternalServerHttp(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ListOfEvents) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c9d2b01EncodeGithubComMironorangeOtusGolangHwHw12131415CalendarInternalServerHttp(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ListOfEvents) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c9d2b01DecodeGithubComMironorangeOtusGolangHwHw12131415CalendarInternalServerHttp(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ListOfEvents) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c9d2b01DecodeGithubComMironorangeOtusGolangHwHw12131415CalendarInternalServerHttp(l, v)
}
func easyjson3c9d2b01DecodeGithubComMironorangeOtusGolangHwHw12131415CalendarInternalServerHttp1(in *jlexer.Lexer, out *EventUpdateAttributes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "summary":
			out.Summary = string(in.String())
		case "startedAt":
			out.StartedAt = int32(in.Int32())
		case "finishedAt":
			out.FinishedAt = int32(in.Int32())
		case "description":
			out.Description = string(in.String())
		case "userUuid":
			out.UserUUID = string(in.String())
		case "notificationAt":
			out.NotificationAt = int32(in.Int32())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c9d2b01EncodeGithubComMironorangeOtusGolangHwHw12131415CalendarInternalServerHttp1(out *jwriter.Writer, in EventUpdateAttributes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"summary\":"
		out.RawString(prefix[1:])
		out.String(string(in.Summary))
	}
	{
		const prefix string = ",\"startedAt\":"
		out.RawString(prefix)
		out.Int32(int32(in.StartedAt))
	}
	{
		const prefix string = ",\"finishedAt\":"
		out.RawString(prefix)
		out.Int32(int32(in.FinishedAt))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"userUuid\":"
		out.RawString(prefix)
		out.String(string(in.UserUUID))
	}
	{
		const prefix string = ",\"notificationAt\":"
		out.RawString(prefix)
		out.Int32(int32(in.NotificationAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EventUpdateAttributes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c9d2b01EncodeGithubComMironorangeOtusGolangHwHw12131415CalendarInternalServerHttp1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EventUpdateAttributes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c9d2b01EncodeGithubComMironorangeOtusGolangHwHw12131415CalendarInternalServerHttp1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EventUpdateAttributes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c9d2b01DecodeGithubComMironorangeOtusGolangHwHw12131415CalendarInternalServerHttp1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EventUpdateAttributes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c9d2b01DecodeGithubComMironorangeOtusGolangHwHw12131415CalendarInternalServerHttp1(l, v)
}
func easyjson3c9d2b01DecodeGithubComMironorangeOtusGolangHwHw12131415CalendarInternalServerHttp2(in *jlexer.Lexer, out *Event) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "uuid":
			out.UUID = string(in.String())
		case "summary":
			out.Summary = string(in.String())
		case "startedAt":
			out.StartedAt = int32(in.Int32())
		case "finishedAt":
			out.FinishedAt = int32(in.Int32())
		case "description":
			out.Description = string(in.String())
		case "userUuid":
			out.UserUUID = string(in.String())
		case "notificationAt":
			out.NotificationAt = int32(in.Int32())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c9d2b01EncodeGithubComMironorangeOtusGolangHwHw12131415CalendarInternalServerHttp2(out *jwriter.Writer, in Event) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"uuid\":"
		out.RawString(prefix[1:])
		out.String(string(in.UUID))
	}
	{
		const prefix string = ",\"summary\":"
		out.RawString(prefix)
		out.String(string(in.Summary))
	}
	{
		const prefix string = ",\"startedAt\":"
		out.RawString(prefix)
		out.Int32(int32(in.StartedAt))
	}
	{
		const prefix string = ",\"finishedAt\":"
		out.RawString(prefix)
		out.Int32(int32(in.FinishedAt))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"userUuid\":"
		out.RawString(prefix)
		out.String(string(in.UserUUID))
	}
	{
		const prefix string = ",\"notificationAt\":"
		out.RawString(prefix)
		out.Int32(int32(in.NotificationAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Event) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c9d2b01EncodeGithubComMironorangeOtusGolangHwHw12131415CalendarInternalServerHttp2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Event) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c9d2b01EncodeGithubComMironorangeOtusGolangHwHw12131415CalendarInternalServerHttp2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Event) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c9d2b01DecodeGithubComMironorangeOtusGolangHwHw12131415CalendarInternalServerHttp2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Event) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c9d2b01DecodeGithubComMironorangeOtusGolangHwHw12131415CalendarInternalServerHttp2(l, v)
}
