// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package broker

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson4086215fDecodeGithubComMironorangeOtusGolangHwHw12131415CalendarInternalBroker(in *jlexer.Lexer, out *Event) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "uuid":
			out.UUID = string(in.String())
		case "summary":
			out.Summary = string(in.String())
		case "startedAt":
			out.StartedAt = int32(in.Int32())
		case "finishedAt":
			out.FinishedAt = int32(in.Int32())
		case "description":
			out.Description = string(in.String())
		case "userUuid":
			out.UserUUID = string(in.String())
		case "notificationAt":
			out.NotificationAt = int32(in.Int32())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4086215fEncodeGithubComMironorangeOtusGolangHwHw12131415CalendarInternalBroker(out *jwriter.Writer, in Event) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"uuid\":"
		out.RawString(prefix[1:])
		out.String(string(in.UUID))
	}
	{
		const prefix string = ",\"summary\":"
		out.RawString(prefix)
		out.String(string(in.Summary))
	}
	{
		const prefix string = ",\"startedAt\":"
		out.RawString(prefix)
		out.Int32(int32(in.StartedAt))
	}
	{
		const prefix string = ",\"finishedAt\":"
		out.RawString(prefix)
		out.Int32(int32(in.FinishedAt))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"userUuid\":"
		out.RawString(prefix)
		out.String(string(in.UserUUID))
	}
	{
		const prefix string = ",\"notificationAt\":"
		out.RawString(prefix)
		out.Int32(int32(in.NotificationAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Event) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4086215fEncodeGithubComMironorangeOtusGolangHwHw12131415CalendarInternalBroker(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Event) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4086215fEncodeGithubComMironorangeOtusGolangHwHw12131415CalendarInternalBroker(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Event) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4086215fDecodeGithubComMironorangeOtusGolangHwHw12131415CalendarInternalBroker(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Event) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4086215fDecodeGithubComMironorangeOtusGolangHwHw12131415CalendarInternalBroker(l, v)
}
