BIN := "./bin/calendar"
PB_EVENTS_PATH="./api/"
PB_GEN_PATH="./internal/pb"
DOCKER_IMG="calendar:develop"

GIT_HASH := $(shell git log --format="%h" -n 1)
LDFLAGS := -X main.release="develop" -X main.buildDate=$(shell date -u +%Y-%m-%dT%H:%M:%S) -X main.gitHash=$(GIT_HASH)

generate:
	[ -d "$(PB_GEN_PATH)" ] && rm -rf $(PB_GEN_PATH) && mkdir -p $(PB_GEN_PATH)
	protoc --proto_path=$(PB_EVENTS_PATH) --go_out=$(PB_GEN_PATH) --go-grpc_out=$(PB_GEN_PATH) $(PB_EVENTS_PATH)/EventService.proto

build:
	go build -v -o $(BIN) -ldflags "$(LDFLAGS)" ./cmd/calendar

run: build
	$(BIN) -config ./configs/config.toml

build-img:
	docker build \
		--build-arg=LDFLAGS="$(LDFLAGS)" \
		-t $(DOCKER_IMG) \
		-f build/Dockerfile .

run-img: build-img
	docker run $(DOCKER_IMG)

version: build
	$(BIN) version

test:
	go test -race ./internal/...

install-lint-deps:
	(which golangci-lint > /dev/null) || curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(shell go env GOPATH)/bin v1.41.1

lint: install-lint-deps
	golangci-lint run ./...

.PHONY: build run build-img run-img version test lint
